import Foundation

/// **Every CSS selector and regex used to read the school website lives here.**
///
/// The site is out of our control (PLAN rule 3) and its markup is generated by
/// Elementor, so class names change without notice. When that happens a
/// contributor should need to edit exactly one file — this one. The failing
/// fixture test names the constant that died.
///
/// Each constant records what it matched and when it was last verified against
/// the live site.
nonisolated enum Selectors {

    // MARK: - Destaques (homepage `/`)

    /// Verified 2026-08-25. The AnyWhere Elementor post widget backed by the
    /// `ultima_hora` post type. The homepage has sibling widgets with
    /// `data-source` of `post`, `destacados_home` and `slider_home` — the
    /// image carousel is `destacados_home`, which is *not* what we want
    /// (PLAN §2.3).
    static let destaquesWidget = "div[data-source=ultima_hora]"

    /// Verified 2026-08-25: 10 matches inside the widget.
    static let destaqueItem = "article.ae-post-list-item"

    /// Verified 2026-08-25: matched "Circular", "Manuais Escolares 26-27", …
    static let destaqueTitle = "span.elementor-icon-list-text"

    /// Verified 2026-08-25: the call-to-action anchor. Its text is the CTA
    /// label ("Agosto 2026", "Consultar") and its href is the only place the
    /// destination URL exists at all (PLAN §2.2).
    static let destaqueLink = "span.elementor-heading-title a[href]"

    // MARK: - Calendário (`/calendario-geral/`)

    /// Verified 2026-08-25. The page renders its accordion **twice** — this
    /// modern `<details>` variant and the legacy one below — as responsive
    /// alternatives. Parse one only, or every event doubles (PLAN §2.5).
    static let calendarAccordionItem = "details.e-n-accordion-item"

    /// Month name inside a `<details>` header, e.g. "Setembro".
    static let calendarAccordionTitle = ".e-n-accordion-item-title-text"

    /// Verified 2026-08-25: legacy Elementor accordion, used only if the
    /// `<details>` variant disappears.
    static let calendarLegacyAccordionItem = ".elementor-accordion .elementor-accordion-item"
    static let calendarLegacyAccordionTitle = "a.elementor-accordion-title"
    static let calendarLegacyAccordionBody = ".elementor-tab-content"

    /// One `<p>` per calendar entry: date line, `<br>`, then event line(s).
    /// **Do not use `<strong>` to find the date** — at least one entry inverts
    /// the bolding. Parse by line position (PLAN §2.5).
    static let calendarEntry = "p"

    static let table = "table"
    static let tableRow = "tr"
    static let tableCell = "td, th"

    /// Verified 2026-08-25: matched against the first cell of a table's first
    /// row to identify it. The page also contains several unrelated cookie
    /// tables, so tables must never be picked by index.
    static let semestersTableMarker = "semestres"
    /// The site currently says "Pausas letivas"; it has also said
    /// "Interrupções letivas". Both are accepted.
    static let breaksTableMarkers = ["pausas", "interrup"]

    // MARK: - Ementas (`/oferecemos/refeitorio-ementas/`)

    /// Verified 2026-08-25: the two tracks ("Pré-Escolar", "Geral") are `h4`
    /// headings, each followed by a `<ul>` of month links. Tracks are read
    /// from these headings, never from the PDF filename.
    static let ementaTrackHeading = "h4"

    /// Verified 2026-08-25: 4 matches, all inside the two track lists. The
    /// footer of the page has more `h4`s but no PDF links, so pairing each PDF
    /// with its nearest preceding `h4` is safe and needs no class names.
    static let ementaLink = "a[href]"

    // MARK: - Regexes

    /// "junho", "JULHO", "Junho" inside a filename or link text.
    /// Portuguese month names, index 0 == January.
    static let monthNames = [
        "janeiro", "fevereiro", "março", "abril", "maio", "junho",
        "julho", "agosto", "setembro", "outubro", "novembro", "dezembro",
    ]

    /// A four-digit year, used to date ementas filenames and calendar tables.
    static let yearPattern = #"(?<!\d)(20\d{2})(?!\d)"#

    /// "10 de setembro 2026" — a fully-qualified date in the two tables.
    static let fullDatePattern = #"(\d{1,2})\s+de\s+([a-zç]+)\s+(20\d{2})"#

    /// The five accordion date formats (PLAN §2.5). Matched in this order;
    /// the first hit wins, so the more specific patterns come first.
    /// Anchored, case-insensitive, tolerant of the trailing whitespace the
    /// site leaves inside the date element.
    static let dateCrossMonthRange = #"^(\d{1,2})\s+de\s+([a-zç]+)\s+a\s+(\d{1,2})\s+de\s+([a-zç]+)$"#
    static let dateRange = #"^(\d{1,2})\s+a\s+(\d{1,2})\s+de\s+([a-zç]+)$"#
    static let dateDiscrete = #"^(\d{1,2})\s+e\s+(\d{1,2})\s+de\s+([a-zç]+)$"#
    static let dateEitherOr = #"^(\d{1,2})\s+ou\s+(\d{1,2})\s+de\s+([a-zç]+)$"#
    static let dateSingle = #"^(\d{1,2})\s+de\s+([a-zç]+)$"#
}
